name: Tests

on:
  push:
    branches:
      - trunk
      - dev-*
      - gh-actions*
  pull_request:
    branches:
      - trunk
      - dev-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'

      - name: Run Tests
        run: go test ./...
